name: Publish to npm

on:
  push:
    branches:
      - release

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          registry-url: https://registry.npmjs.org
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run Tests
        run: npm test

      - name: Build Package
        run: npm run build

      - name: Read package information
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Check npm version
        id: npm
        run: |
          PACKAGE="${{ steps.package.outputs.name }}"
          VERSION="${{ steps.package.outputs.version }}"

          echo "Checking $PACKAGE@$VERSION"

          if npm view "$PACKAGE@$VERSION" version > /dev/null 2>&1; then
            echo "exists=true" >> $GITHUB_OUTPUT
            echo "Version already exists."
          else
            echo "exists=false" >> $GITHUB_OUTPUT
            echo "New version detected."
          fi

      - name: Publish to npm
        if: steps.npm.outputs.exists == 'false'
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Git Tag
        if: steps.npm.outputs.exists == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const version='v${{ steps.package.outputs.version }}';

            try{
              await github.rest.git.createRef({
                owner: context.repo.owner,
                repo: context.repo.repo,
                ref:`refs/tags/${version}`,
                sha:context.sha
              });

              console.log(`Created ${version}`);
            }catch(e){
              console.log("Tag already exists");
            }

      - name: Create GitHub Release
        if: steps.npm.outputs.exists == 'false'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.package.outputs.version }}
          generate_release_notes: true
          make_latest: true

      - name: Summary
        run: |
          if [ "${{ steps.npm.outputs.exists }}" = "true" ]; then
            echo "Package already exists on npm."
            echo "Publish skipped."
          else
            echo "Published successfully."
          fi